# Generated by Django 5.0.14 on 2026-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timelog',
            name='session_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Work'), ('BREAK', 'Break'), ('OVERTIME', 'Overtime')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this session'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['user', 'date'], name='time_logs_user_id_cb972a_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['date', 'check_in_time'], name='time_logs_date_cf8e17_idx'),
        ),
    ]
