# Generated by Django 5.0.14 on 2026-01-11 06:32

import apps.pipeline.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('NEW_REQUEST', 'New Request'), ('ENGAGED', 'Engaged'), ('ESTIMATE_IN_PROGRESS', 'Estimate In Progress'), ('ESTIMATE_SENT', 'Estimate Sent'), ('FOLLOW_UP', 'Follow Up'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost'), ('DECLINED_TO_BID', 'Declined to Bid')], db_index=True, default='NEW_REQUEST', max_length=30)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_lost_reason', models.CharField(blank=True, choices=[('PRICE', 'Price Too High'), ('TIMELINE', 'Timeline Issues'), ('COMPETITOR', 'Lost to Competitor'), ('UNRESPONSIVE', 'Client Unresponsive'), ('OTHER', 'Other')], max_length=20)),
                ('declined_reason', models.CharField(blank=True, choices=[('TOO_SMALL', 'Project Too Small'), ('NOT_OUR_SCOPE', 'Not Our Scope of Work'), ('TIMING', 'Timing Not Right'), ('CAPACITY', 'No Capacity'), ('OTHER', 'Other')], max_length=20)),
                ('close_notes', models.TextField(blank=True, help_text='Additional notes about why the deal was closed/declined')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Final value for closed won deals', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('probability', models.IntegerField(default=50, help_text='Probability of winning (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('estimator', models.ForeignKey(blank=True, help_text='Assigned estimator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_deals', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Primary owner of this deal', on_delete=django.db.models.deletion.PROTECT, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deals',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Deal Created'), ('STAGE_CHANGED', 'Stage Changed'), ('EDITED', 'Deal Edited'), ('FILE_ADDED', 'File Added'), ('FILE_REMOVED', 'File Removed'), ('COMMENT', 'Comment Added'), ('ASSIGNED', 'Assignment Changed')], max_length=20)),
                ('description', models.TextField()),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pipeline.deal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal Activity',
                'verbose_name_plural': 'Deal Activities',
                'db_table': 'deal_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.pipeline.models.deal_file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('ESTIMATE', 'Estimate'), ('CONTRACT', 'Contract'), ('PROPOSAL', 'Proposal'), ('DRAWING', 'Drawing/Plans'), ('PHOTO', 'Photo'), ('CORRESPONDENCE', 'Correspondence'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pipeline.deal')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='pipeline.dealfile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_deal_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal File',
                'verbose_name_plural': 'Deal Files',
                'db_table': 'deal_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage', 'position'], name='deals_stage_489ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['owner', 'stage'], name='deals_owner_i_991c52_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'stage'], name='deals_client__b65e00_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_date'], name='deals_expecte_53925b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='deals_created_7fb120_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage_changed_at'], name='deals_stage_c_740cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['deal', 'created_at'], name='deal_activi_deal_id_9be0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='dealactivity',
            index=models.Index(fields=['activity_type'], name='deal_activi_activit_e17159_idx'),
        ),
        migrations.AddIndex(
            model_name='dealfile',
            index=models.Index(fields=['deal', 'file_type'], name='deal_files_deal_id_34aab0_idx'),
        ),
        migrations.AddIndex(
            model_name='dealfile',
            index=models.Index(fields=['deal', 'is_current'], name='deal_files_deal_id_cf8d43_idx'),
        ),
        migrations.AddIndex(
            model_name='dealfile',
            index=models.Index(fields=['uploaded_at'], name='deal_files_uploade_390c98_idx'),
        ),
    ]
