# Generated by Django 5.0.14 on 2026-01-13 05:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='Person overseeing the deal/project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='site_officer',
            field=models.ForeignKey(blank=True, help_text='Field technician who visits the site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_officer_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DealComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_comments', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pipeline.deal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pipeline.dealcomment')),
            ],
            options={
                'verbose_name': 'Deal Comment',
                'verbose_name_plural': 'Deal Comments',
                'db_table': 'deal_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deal', '-created_at'], name='deal_commen_deal_id_2dcf7b_idx'), models.Index(fields=['parent'], name='deal_commen_parent__599929_idx')],
            },
        ),
        migrations.CreateModel(
            name='DealSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SITE_VISIT', 'Site Visit'), ('INSPECTION', 'Inspection'), ('INSTALLATION', 'Installation'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('FOLLOW_UP', 'Follow-up'), ('OTHER', 'Other')], max_length=20)),
                ('custom_event_type', models.CharField(blank=True, help_text='Custom event type when "Other" is selected', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Duration in hours', max_digits=4)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('location_notes', models.TextField(blank=True, help_text='Specific location within the property')),
                ('access_instructions', models.TextField(blank=True, help_text='Gate codes, parking info, contact on arrival, etc.')),
                ('equipment_needed', models.TextField(blank=True, help_text='Tools, parts, or equipment required for this visit')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 Weeks'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMIANNUAL', 'Every 6 Months'), ('ANNUAL', 'Annual')], max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes from completing this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person assigned to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pipeline.deal')),
                ('parent_schedule', models.ForeignKey(blank=True, help_text='Parent recurring schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_instances', to='pipeline.dealschedule')),
            ],
            options={
                'verbose_name': 'Deal Schedule',
                'verbose_name_plural': 'Deal Schedules',
                'db_table': 'deal_schedules',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'indexes': [models.Index(fields=['deal', 'scheduled_date'], name='deal_schedu_deal_id_cbab33_idx'), models.Index(fields=['assigned_to', 'scheduled_date'], name='deal_schedu_assigne_4d8020_idx'), models.Index(fields=['status'], name='deal_schedu_status_d84533_idx'), models.Index(fields=['scheduled_date'], name='deal_schedu_schedul_f7841a_idx')],
            },
        ),
    ]
