# Generated by Django 5.0.14 on 2026-01-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pipeline",
            "0002_deal_project_manager_deal_site_officer_dealcomment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dealschedule",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dealschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_REQUEST", "New Request"),
                    ("SITE_OFFICER_ASSIGNED", "Site Officer Assigned"),
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="NEW_REQUEST",
                max_length=30,
            ),
        ),
    ]
